[project]
name = "ashmeet"
version = "0.1.0"
description = "Deep Learning & Big Data Lab"
requires-python = ">=3.9"
dependencies = [
    "tensorflow>=2.10.0",
    "pyhive[hive]",
    "pandas",
    "mlflow"
]
